sudo: required

language: minimal

services:
  - docker



before_install:
  - docker build -t infra-anoop/complex-test -f ./client/Dockerfile.dev ./client
  - docker run infra-anoop/complex-test npm test -- --coverage

scripts:
  - docker run infra-anoop/complex-test npm test -- --coverage

after_success:
  - docker build -t anoopagarwal/complex-client ./client
  - docker build -t anoopagarwal/complex-server ./server
  - docker build -t anoopagarwal/complex-worker ./worker
  - docker build -t anoopagarwal/complex-nginx ./nginx
#login
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_ID --password-stdin
#push to docker hub
  - docker push anoopagarwal/complex-client
  - docker push anoopagarwal/complex-server
  - docker push anoopagarwal/complex-worker
  - docker push anoopagarwal/complex-nginx

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  region: us-east-2
  app: complexweb
  env: Complexweb-env
  bucket_name: elasticbeanstalk-us-east-2-074724716397
  bucket_path: complexweb
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
