sudo: required

language: minimal

services:
  - docker



before_install:
  - docker build -t infra-anoop/complex-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run infra-anoop/complex-test npm test -- --coverage

after_success:
  - docker build -t complex-client ./client
  - docker build -t complex-server ./server
  - docker build -t complex-worker ./worker
  - docker build -t complex-nginx ./nginx
#login
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_ID --password-stdin
#push to docker hub
  - docker push complex-client
  - docker push complex-server
  - docker push complex-worker
  - docker push complex-nginx
